spring:
  application:
    name: hewie_blog_system

  datasource:
    url:  jdbc:mysql://192.168.244.128:3306/hewie_blog_system?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 102426
  redis:
    host: 192.168.244.128
    port: 6379
    password: 102426
  data:
    solr:
      host: http://192.168.244.128:8983/solr/hewie_blog_core

server:
  port: 2020

hewie.blog.image.save-path: F:\Blog\images
# 2M
hewie.blog.image.max-size: 1048576

# 控制swag的开关
hewie.blog.swagger.enable: true
